export const TICKET_STATUS = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  ON_HOLD: 'ON_HOLD',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
} as const;

export const TICKET_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
} as const;

export const TICKET_TYPE = {
  REQUEST: 'REQUEST',
  INCIDENT: 'INCIDENT',
  ACCESS: 'ACCESS',
  HARDWARE: 'HARDWARE',
  SOFTWARE: 'SOFTWARE',
  OTHER: 'OTHER'
} as const;

export type TicketStatusName = (typeof TICKET_STATUS)[keyof typeof TICKET_STATUS];

export const LEGACY_STATUS_TO_CANONICAL: Record<string, TicketStatusName> = {
  Nuevo: TICKET_STATUS.NEW,
  NUEVO: TICKET_STATUS.NEW,
  'En progreso': TICKET_STATUS.IN_PROGRESS,
  EN_PROGRESO: TICKET_STATUS.IN_PROGRESS,
  'En espera': TICKET_STATUS.ON_HOLD,
  EN_ESPERA: TICKET_STATUS.ON_HOLD,
  Resuelto: TICKET_STATUS.RESOLVED,
  RESUELTO: TICKET_STATUS.RESOLVED,
  Cerrado: TICKET_STATUS.CLOSED,
  CERRADO: TICKET_STATUS.CLOSED
};

export const LEGACY_PRIORITY_TO_CANONICAL: Record<string, string> = {
  Baja: TICKET_PRIORITY.LOW,
  BAJA: TICKET_PRIORITY.LOW,
  Media: TICKET_PRIORITY.MEDIUM,
  MEDIA: TICKET_PRIORITY.MEDIUM,
  Alta: TICKET_PRIORITY.HIGH,
  ALTA: TICKET_PRIORITY.HIGH,
  Crítica: TICKET_PRIORITY.CRITICAL,
  CRITICA: TICKET_PRIORITY.CRITICAL,
  CRÍTICA: TICKET_PRIORITY.CRITICAL
};

export const LEGACY_TYPE_TO_CANONICAL: Record<string, string> = {
  PETICIÓN: TICKET_TYPE.REQUEST,
  PETICION: TICKET_TYPE.REQUEST,
  INCIDENCIA: TICKET_TYPE.INCIDENT,
  ACCESO: TICKET_TYPE.ACCESS,
  OTROS: TICKET_TYPE.OTHER
};

export const STATUS_TRANSITIONS: Record<TicketStatusName, TicketStatusName[]> = {
  [TICKET_STATUS.NEW]: [TICKET_STATUS.IN_PROGRESS, TICKET_STATUS.ON_HOLD],
  [TICKET_STATUS.IN_PROGRESS]: [TICKET_STATUS.ON_HOLD, TICKET_STATUS.RESOLVED],
  [TICKET_STATUS.ON_HOLD]: [TICKET_STATUS.IN_PROGRESS, TICKET_STATUS.RESOLVED],
  [TICKET_STATUS.RESOLVED]: [TICKET_STATUS.NEW, TICKET_STATUS.IN_PROGRESS, TICKET_STATUS.ON_HOLD, TICKET_STATUS.CLOSED],
  [TICKET_STATUS.CLOSED]: []
};

export const normalizeStatusName = (value: string) => LEGACY_STATUS_TO_CANONICAL[value] ?? value;
export const normalizePriorityName = (value: string) => LEGACY_PRIORITY_TO_CANONICAL[value] ?? value;
export const normalizeTypeName = (value: string) => LEGACY_TYPE_TO_CANONICAL[value] ?? value;
